# Generated by Django 5.0.6 on 2024-10-19 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mxl_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mxl_file', models.FileField(null=True, unique=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mxl', 'musicxml'])])),
            ],
        ),
        migrations.CreateModel(
            name='Tester_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='video_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_files', models.FileField(null=True, unique=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
            ],
        ),
    ]
